### ISSUE TITLE
Do deltaSVM support InDel predictions?

### ISSUE THREAD

**Issue by ChevyXu** [ren-lab/deltaSVM#1]
Hi, Renlab members,

Thanks for developing such great tools to handle TFs binding prediction.

I'm wondering whether **deltaSVM** could support the **InDels** predicotion, cause the InDels always are the may reason forTFs binding difference.

Sincerely

**Comment by yjqiu** [comment]
Thanks for your interest! In principle, the model should work on indels. However, we only benchmarked it on SNPs and all thresholds are selected based on SNPs, so you may need to take your own risk.
