### ISSUE TITLE
SVM models missing

### ISSUE THREAD

**Issue by BeeSting-pgm** [ren-lab/deltaSVM#2]
The complete set of models are not present in the all_models folder

**Comment by yjqiu** [comment]
Can you comment on which models are missing?

**Comment by BeeSting-pgm** [comment]
in the all_models folder they don't contain files, just paths.

**Comment by yjqiu** [comment]
@BeeSting-pgm Thanks for spotting the missing files. The files have been updated now.

**Comment by rmd13** [comment]
The uploaded files cannot be download. It says file is too large

**Comment by yjqiu** [comment]
Looks like the file is too large for our GitHub space. I have updated the link to our server. @BeeSting-pgm @rmd13

**Comment by rmd13** [comment]
Hi, if to use all models, does the obs_threshold and pbs_threshold match all transcription factors, or only the 94 ones？ Thanks

**Comment by yjqiu** [comment]
@rmd13 No, the thresholds only work for 94 confident models. We don't suggest users to use all models since they are not validated or failed during our benchmark. They are only for advanced users to explore instead of making predictions.

**Comment by rmd13** [comment]
In the results table there are 2 columes: 	"deltaSVM_score" and "preferred_allele". Often there are SNP-TF lines shows relative high value but the "preferred_allele" shows "None", compared to the relative lower "deltaSVM_score" but "Gain". How to interpret this scenario? Does the "Gain" means allelel bind stronger to SNP than allele1? But sometims allele2_bind is -0.706563 but allele1_bind is 0.562300, lookes the reverse. Thanks.

**Comment by yjqiu** [comment]
@rmd13 Do you mean for additional models or 94 models? For additional models, run.sh will not work. I have updated the readme to include more details. For 94 models, do you mind create a new issue since it is a separate problem.

**Comment by yjqiu** [comment]
Close issues.
