### ISSUE TITLE
demo log shows q lot of wraning: : 'N' at (null)(19) is not a valid nucleotide. Only ACGT are allowed

### ISSUE THREAD

**Issue by rmd13** [ren-lab/deltaSVM#3]
Hi,
I run a demo inside and see a lot of warning message in log file.
 Is this normal, or is there something wrong? Thank you

INFO 2021-02-23 11:57:28: Number of threads is set to 1
INFO 2021-02-23 11:57:28: load model /media/sf_deltaSVM/deltaSVM-master/models/ETV2_eDBD_4_KO_TTCGGG40NGAG.subsample_20000.10mer.model.txt
WARN 2021-02-23 11:57:28: 'N' at (null)(19) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(19) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(19) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(19) is not a valid nucleotide. Only ACGT are allowed
INFO 2021-02-23 11:57:28: reading... 1000/23055
WARN 2021-02-23 11:57:28: 'N' at (null)(28) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(30) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(31) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(32) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(33) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(19) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(31) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(32) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(19) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(28) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(30) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(31) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(32) is not a valid nucleotide. Only ACGT are allowed
WARN 2021-02-23 11:57:28: 'N' at (null)(33) is not a valid nucleotide. Only ACGT are allowed

.......

**Comment by rmd13** [comment]
Is there way to turn off thw warning to save more time? Thanks

**Comment by yjqiu** [comment]
The model is not designed to test sequence with N. You should replace N with two alleles of the SNP instead.

**Comment by yjqiu** [comment]
Close the issue due to no follow up. Feel free to reopen if you have additional questions.
