### ISSUE TITLE
Increase thread number from 1 to 16 makes program much slower

### ISSUE THREAD

**Issue by rmd13** [ren-lab/deltaSVM#4]
Hi,

To speed up the process, I set the shell script's all the  -T parameter to 16 (because trial shows only 1,4,16 allowed), however, the calculation is much slower and cannot finish after long time. Is there a possible reason for this? Thanks

**Comment by yjqiu** [comment]
For issues with gkmpredict, you may need to consult authors of gkmpredict. Or a better way to speed up is to run gkmpredict for multiple models parallel. But you will need to modify the script yourself.

**Comment by yjqiu** [comment]
Close the issue due to no follow up. Feel free to reopen if you have additional questions.
