### ISSUE TITLE
hg38 reference genome?

### ISSUE THREAD

**Issue by RegnerM2015** [ren-lab/deltaSVM#5]
Hi @yjqiu 

Does deltaSVM work with the hg38 reference? Will the models be transferable? 

Thanks!

**Comment by RegnerM2015** [comment]
Just figured this one out! From the README:

Other genome builds can also be used, but you need to make sure the SNP file and fasta file are from the same genome build. Also, you need to change hg19.fa in the run.sh to corresponding files.

**Comment by TaoHJiang** [comment]
Hi @yjqiu

Does deltaSVM work with reference sequences for other species? 
Thanks!

**Comment by yjqiu** [comment]
@TaoHJiang I don't think so because the SELEX data is generated for human TFs and TFs from difference species may not share the same sequence specificities.
