### ISSUE TITLE
Run time for 1 million SNPs?

### ISSUE THREAD

**Issue by RegnerM2015** [ren-lab/deltaSVM#6]
Hi @yjqiu 

Would you be able to estimate the expected runtime for deltaSVM on over 1 million SNPs? Does deltaSVM scale to this many SNPs?

Thanks!

**Comment by yjqiu** [comment]
Hi @RegnerM2015, thanks for asking. We do run it for a few millions SNPs as the data we included in our supplementary data for all common SNPs. I tested in our server and ~1k SNPs takes 10 minutes. So 1 million SNPs may take ~7 days. A better way to speed up is to run gkmpredict for multiple models parallel. But you will need to modify the script yourself.

**Comment by yjqiu** [comment]
Close the issue due to no follow up. Feel free to reopen if you have additional questions.
