### ISSUE TITLE
Interpert results for Gain

### ISSUE THREAD

**Issue by rmd13** [ren-lab/deltaSVM#7]
I run the deltaSVM  online using demo 3 SNPs  provided  online server as example. In the results table there are 2 columes: "deltaSVM_score" and "preferred_allele".Sometimes there are SNP-TF lines shows relative high delta_SVM value but the "preferred_allele" shows "None", while there are  relative a little bit  lower "deltaSVM_score" but "preferred_allele" shows "Gain". How to interpret this scenario? Was the "preferred_allele" determined not only by delta_SVM score but also by the score for each alternative allele？ Does the "Gain" means allelel2 bind stronger to SNP than allele1? But sometims allele2_bind is -0.706563 but allele1_bind is 0.562300, lookes the reverse but still shows 'Gain'. Thanks.

**Comment by yjqiu** [comment]
@rmd13 We make predictions by comparing deltaSVM scores with the experimental thresholds as defined by median value of pbSNPs identified in SNP-SELEX. The absolute scale of the deltaSVM score is NOT informative especially compared across TFs.  

Yes. Gain means 2nd allele is stronger than 1st. Take SNP chr1_100_A_G as an example, gain means TF binds G stronger than A.

The bind score is predicted by gkm-SVM which measures the binding strength of the entire sequence. But difference between gkm-SVM is not used to measure allelic binding and it is only used to measure if the sequence can be bind by the TF. Allelic binding is measured by deltaSVM scores.
