### ISSUE TITLE
deltaSVM score

### ISSUE THREAD

**Issue by BenxiaHu** [ren-lab/deltaSVM#8]
Hello,
    I ran deltaSVM on my sequences, but it is hard for me to interpret the result. For example, the last column (preferred_allele) is None, while some values in the deltaSVM_score column is greater than 1. 

![image](https://user-images.githubusercontent.com/12387462/118730867-44e36580-b806-11eb-9405-2a0a7155c80b.png)

**Comment by yjqiu** [comment]
Hi @BioEpi, it is tricky to make a binary call by the deltaSVM score itself without any context. In our website, we used deltaSVM scores for known allelic binding SNPs (pbSNPs) as the threshold. The score may be high (>1) by it is not higher than known pbSNPs so it is determined as None. But you can always use your way to determine threshold.

**Comment by yjqiu** [comment]
Close the issue for now. May reopen for other questions.
