### ISSUE TITLE
Meaning of "seq_binding" in deltaSVM output

### ISSUE THREAD

**Issue by tianwen0003** [ren-lab/deltaSVM#9]
Hi @yjqiu
I am cofused about exact meaning of "seq_binding" column in deltaSVM output, is that just gotten from a ChIP-Seq data of certain cell type or speculated from algorithm?

**Comment by yjqiu** [comment]
Hi @tianwen0003 It is the predicted score by gkm-SVM.

**Comment by tianwen0003** [comment]
Hi @yjqiu
Thanks for your reply

So is it mean the "Y" is more creadible than "N" when I want to explore the effects of single nucleotide variant on the TF binding?

I also have another question: for several significant eQTLs that effect the binding of  same TF in one tissue, if I assune all prediced results are ture positive, is that mean their eQTL effect size should be positively correlated with their deltaSVM?

**Comment by yjqiu** [comment]
@tianwen0003 Please see below for my answers.

Y/N means if the differential binding score exceed predefined thresholds. If you only care about binary outcome (different binding or not), you can only look at Ys.

That's a good question. But I would NOT assume that all eQTLs to be true positives and be positively correlated with deltaSVM scores. First, not all eQTLs are casual and most of them are simply in LD with true casual variants. Second, even if the eQTL is the casual variant, it may not affect gene expression via TF binding. For example, it may affect splicing instead. Third, even if the eQTL affects gene expression via TF binding, it is hard to predict the direction of TF binding change. Sometimes stronger TF binding leads to higher expression while weaker TF binding leads to higher expression in other cases. In addition, the models may not cover all TFs and in vitro prediction by SELEX may not be reflect in vivo TF binding.

**Comment by tianwen0003** [comment]
Hi @yjqiu
Thanks very much for your nice responsive, I think I did underestimate the complexity of gene regulation. I will consider this question more carefully. Thank you again.

**Comment by txw-lab** [comment]
> Hi @yjqiu Thanks very much for your nice responsive, I think I did underestimate the complexity of gene regulation. I will consider this question more carefully. Thank you again.

Excuse me. It seems that you haved runned the deltaSVM successfully. Now the resources file isn't available, could you please send me the files (i know the hg19 is too large, so could you send me the others)? Thanks so much. My Email is : 1610305211@bjmu.edu.cn

**Comment by yjqiu** [comment]
@txw-lab 

Sorry for the broken link and delayed reply. We have some problems with our server and I put the files in Dropbox for now. You can find the links below. You may use the standard hg19 reference genome in fasta format for the reference genome.

https://www.dropbox.com/s/bde2emzm9j3n1y4/models.weights.txt.gz?dl=0
https://www.dropbox.com/s/o04zm5c9xao907b/threhsolds.obs.tsv?dl=0
https://www.dropbox.com/s/rp9nb7gltdxgqkg/threhsolds.pbs.tsv?dl=0

We will fix the link as soon as possible and let me know if you have any other problems.
